// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VidCV.Web.Data;

#nullable disable

namespace VidCV.Web.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260412000000_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VidCV.Web.Models.CvProfile", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                b.Property<DateTime?>("CompletedAt").HasColumnType("datetime2");
                b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
                b.Property<string>("CvFileName").HasMaxLength(300).HasColumnType("nvarchar(300)");
                b.Property<string>("CvFilePath").HasMaxLength(500).HasColumnType("nvarchar(500)");
                b.Property<string>("Education").HasMaxLength(2000).HasColumnType("nvarchar(2000)");
                b.Property<string>("Email").IsRequired().HasMaxLength(200).HasColumnType("nvarchar(200)");
                b.Property<string>("Experience").HasMaxLength(4000).HasColumnType("nvarchar(4000)");
                b.Property<string>("FullName").IsRequired().HasMaxLength(200).HasColumnType("nvarchar(200)");
                b.Property<string>("JobTitle").HasMaxLength(200).HasColumnType("nvarchar(200)");
                b.Property<string>("LinkedInUrl").HasMaxLength(500).HasColumnType("nvarchar(500)");
                b.Property<string>("Phone").HasMaxLength(50).HasColumnType("nvarchar(50)");
                b.Property<string>("Skills").HasMaxLength(2000).HasColumnType("nvarchar(2000)");
                b.Property<int>("Status").HasColumnType("int");
                b.Property<string>("Summary").HasMaxLength(2000).HasColumnType("nvarchar(2000)");
                b.Property<string>("VideoPath").HasMaxLength(500).HasColumnType("nvarchar(500)");
                b.Property<string>("VideoScript").HasMaxLength(4000).HasColumnType("nvarchar(4000)");
                b.Property<string>("VideoUrl").HasMaxLength(500).HasColumnType("nvarchar(500)");
                b.HasKey("Id");
                b.HasIndex("CreatedAt");
                b.HasIndex("Email");
                b.ToTable("CvProfiles");
            });

            modelBuilder.Entity("VidCV.Web.Models.VideoTemplate", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                b.Property<string>("AccentColor").IsRequired().HasMaxLength(20).HasColumnType("nvarchar(20)");
                b.Property<string>("BackgroundColor").IsRequired().HasMaxLength(20).HasColumnType("nvarchar(20)");
                b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
                b.Property<string>("Description").IsRequired().HasMaxLength(500).HasColumnType("nvarchar(500)");
                b.Property<int>("DurationSeconds").HasColumnType("int");
                b.Property<string>("FontFamily").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
                b.Property<bool>("IsActive").HasColumnType("bit");
                b.Property<string>("Name").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
                b.Property<string>("TextColor").IsRequired().HasMaxLength(20).HasColumnType("nvarchar(20)");
                b.HasKey("Id");
                b.ToTable("VideoTemplates");
            });
#pragma warning restore 612, 618
        }
    }
}
