// <auto-generated />
using System;
using AgoneSentimentSales.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AgoneSentimentSales.Infrastructure.Migrations
{
    [DbContext(typeof(SentimentSalesDbContext))]
    [Migration("20260603145108_AddScraperConfigurations")]
    partial class AddScraperConfigurations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("sentimentsales")
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AgoneSentimentSales.Domain.Entities.ApiRequestLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ClientIp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("DurationMs")
                        .HasColumnType("bigint");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StatusCode")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ApiRequestLogs", "sentimentsales");
                });

            modelBuilder.Entity("AgoneSentimentSales.Domain.Entities.ExecutiveContact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AreasOfResponsibility")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EstimatedEmailFormat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExecutiveName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("bit");

                    b.Property<string>("LinkedInUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LseCompanyId")
                        .HasColumnType("int");

                    b.Property<int>("RoleType")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LseCompanyId");

                    b.ToTable("ExecutiveContacts", "sentimentsales");
                });

            modelBuilder.Entity("AgoneSentimentSales.Domain.Entities.ItBudgetBreakdown", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AnnualRevenueGbpB")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ApplicationLicensingGbpM")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ApplicationSupportGbpM")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CapexGbpM")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CloudInfrastructureGbpM")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CyberSecurityGbpM")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DataAndAiProjectsGbpM")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("EndUserComputingGbpM")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("EstimatedItBudgetGbpM")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("EstimationMethodology")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FiscalYear")
                        .HasColumnType("int");

                    b.Property<decimal>("ItAsPercentOfRevenue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("LseCompanyId")
                        .HasColumnType("int");

                    b.Property<decimal>("ManagedServicesGbpM")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OffshoreResourceCostGbpM")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OnshoreResourceCostGbpM")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OpexGbpM")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OtherGbpM")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("LseCompanyId")
                        .IsUnique();

                    b.ToTable("ItBudgets", "sentimentsales");
                });

            modelBuilder.Entity("AgoneSentimentSales.Domain.Entities.LeadGenerationData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AsiaOperations")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DigitalRoles")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HiringTrends")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItAnnouncements")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LeadScore")
                        .HasColumnType("int");

                    b.Property<int>("LseCompanyId")
                        .HasColumnType("int");

                    b.Property<string>("PainPoints")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RenewalCycle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LseCompanyId")
                        .IsUnique();

                    b.ToTable("LeadGenerationData", "sentimentsales");
                });

            modelBuilder.Entity("AgoneSentimentSales.Domain.Entities.LseCompany", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DataSourceNotes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("HasAsiaSubsidiary")
                        .HasColumnType("bit");

                    b.Property<string>("HqLocation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IndustryGroup")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastResearchedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("MarketCapGbpB")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OffshoringStatus")
                        .HasColumnType("int");

                    b.Property<string>("PrimaryOffshoreLocations")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Rank")
                        .HasColumnType("int");

                    b.Property<string>("Sector")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Rank");

                    b.HasIndex("Ticker")
                        .IsUnique();

                    b.ToTable("Companies", "sentimentsales");
                });

            modelBuilder.Entity("AgoneSentimentSales.Domain.Entities.OutsourcingPartner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContractType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("EstimatedAnnualContractGbpM")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("LseCompanyId")
                        .HasColumnType("int");

                    b.Property<string>("OffshoreDeliveryCenters")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PartnershipDuration")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrimaryPartners")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecondaryPartners")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LseCompanyId")
                        .IsUnique();

                    b.ToTable("OutsourcingPartners", "sentimentsales");
                });

            modelBuilder.Entity("AgoneSentimentSales.Domain.Entities.ResearchJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OutputFilePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProcessedCount")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TargetCompanyCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ResearchJobs", "sentimentsales");
                });

            modelBuilder.Entity("AgoneSentimentSales.Domain.Entities.ScraperConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BaseUrlTemplate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DelayMsMax")
                        .HasColumnType("int");

                    b.Property<int>("DelayMsMin")
                        .HasColumnType("int");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<int>("MaxItemsToScrape")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("SourceType")
                        .IsUnique();

                    b.ToTable("ScraperConfigurations", "sentimentsales");
                });

            modelBuilder.Entity("AgoneSentimentSales.Domain.Entities.SourceExtractionEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ConfidenceScore")
                        .HasColumnType("float");

                    b.Property<DateTime>("ExtractedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExtractedValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("LseCompanyId")
                        .HasColumnType("int");

                    b.Property<string>("RawSnippet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ResearchJobId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SourceLabel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SourceUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LseCompanyId");

                    b.HasIndex("ResearchJobId");

                    b.ToTable("SourceExtractionEvents", "sentimentsales");
                });

            modelBuilder.Entity("AgoneSentimentSales.Domain.Entities.SourcedDataPoint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("ConfidenceScore")
                        .HasColumnType("float");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FieldValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LseCompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SourceUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LseCompanyId");

                    b.HasIndex("LseCompanyId", "FieldName");

                    b.ToTable("SourcedDataPoints", "sentimentsales");
                });

            modelBuilder.Entity("AgoneSentimentSales.Domain.Entities.TechnologyStrategy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AiMlPrograms")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AutomationFocus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CloudStrategy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DataAnalytics")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DigitalMaturity")
                        .HasColumnType("int");

                    b.Property<string>("DigitalTransformationEvidence")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KeyTechInitiatives")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LseCompanyId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LseCompanyId")
                        .IsUnique();

                    b.ToTable("TechnologyStrategies", "sentimentsales");
                });

            modelBuilder.Entity("AgoneSentimentSales.Domain.Entities.ExecutiveContact", b =>
                {
                    b.HasOne("AgoneSentimentSales.Domain.Entities.LseCompany", "Company")
                        .WithMany("ExecutiveContacts")
                        .HasForeignKey("LseCompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("AgoneSentimentSales.Domain.Entities.ItBudgetBreakdown", b =>
                {
                    b.HasOne("AgoneSentimentSales.Domain.Entities.LseCompany", "Company")
                        .WithOne("ItBudget")
                        .HasForeignKey("AgoneSentimentSales.Domain.Entities.ItBudgetBreakdown", "LseCompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("AgoneSentimentSales.Domain.Entities.LeadGenerationData", b =>
                {
                    b.HasOne("AgoneSentimentSales.Domain.Entities.LseCompany", "Company")
                        .WithOne("LeadGeneration")
                        .HasForeignKey("AgoneSentimentSales.Domain.Entities.LeadGenerationData", "LseCompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("AgoneSentimentSales.Domain.Entities.OutsourcingPartner", b =>
                {
                    b.HasOne("AgoneSentimentSales.Domain.Entities.LseCompany", "Company")
                        .WithOne("OutsourcingPartner")
                        .HasForeignKey("AgoneSentimentSales.Domain.Entities.OutsourcingPartner", "LseCompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("AgoneSentimentSales.Domain.Entities.SourceExtractionEvent", b =>
                {
                    b.HasOne("AgoneSentimentSales.Domain.Entities.LseCompany", "Company")
                        .WithMany()
                        .HasForeignKey("LseCompanyId");

                    b.HasOne("AgoneSentimentSales.Domain.Entities.ResearchJob", "ResearchJob")
                        .WithMany()
                        .HasForeignKey("ResearchJobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("ResearchJob");
                });

            modelBuilder.Entity("AgoneSentimentSales.Domain.Entities.SourcedDataPoint", b =>
                {
                    b.HasOne("AgoneSentimentSales.Domain.Entities.LseCompany", "Company")
                        .WithMany()
                        .HasForeignKey("LseCompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("AgoneSentimentSales.Domain.Entities.TechnologyStrategy", b =>
                {
                    b.HasOne("AgoneSentimentSales.Domain.Entities.LseCompany", "Company")
                        .WithOne("TechnologyStrategy")
                        .HasForeignKey("AgoneSentimentSales.Domain.Entities.TechnologyStrategy", "LseCompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("AgoneSentimentSales.Domain.Entities.LseCompany", b =>
                {
                    b.Navigation("ExecutiveContacts");

                    b.Navigation("ItBudget");

                    b.Navigation("LeadGeneration");

                    b.Navigation("OutsourcingPartner");

                    b.Navigation("TechnologyStrategy");
                });
#pragma warning restore 612, 618
        }
    }
}
