// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using AGONECompliance.API.Data;

#nullable disable

namespace AGONECompliance.API.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260418000000_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11").HasAnnotation("Relational:MaxIdentifierLength", 128);
            modelBuilder.HasDefaultSchema("compliance");
            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);
        }
    }
}
